# Welcome to Jekyll!
#

# Site settings
title: Nathan Robert Chan
description: |
  Graduate Student | Exploring Life
owner: Nathan Robert Chan
first_published: 2018
email: nathanrobert.chan@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nathanchan13.github.io/" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/nathanchan13
  linkedin-square: https://www.linkedin.com/in/nathanrobert-chan/
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: httpes://instagram.com
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
